### ISSUE TITLE
default access mode for PVC

### ISSUE THREAD

**Issue by nauni77** [neuvector/neuvector-helm#110]
Hello,

I think the default access mode should be 
```
controller:
  pvc:
    enabled: true
    accessModes:
      - ReadWriteOnce
```

ReadWriteMany is often not supported and I think this should be configured if needed. Default should IMHO be `ReadWriteOnce`.

Regards, Oli

**Comment by gtam** [comment]
The recommendation to run 3 controller replicas makes RWX a requirement.

**Comment by nauni77** [comment]
If these three controllers will use the same pvc - this is correct.

As we bought your licenses we got a big yaml from you and there was only one controller and one pvc. I think the most companies will use ReadWriteOnce for automatic provisioning (for example ceph cluster with rbd) - with such a environment your deployment is not working.

If you don't change the default I will adopt the settings at our deployment (this is no problem) - but I think the most companies will use ReadWriteOnce access mode for automatic provisioning and this will cause problems with your default settings.

Why you _now_ need three controllers and earlier one controller worked for you?

**Comment by nauni77** [comment]
If someone else have this issue ... we use now:

```
controller:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  pvc:
    enabled: true
    accessModes:
      - ReadWriteOnce
```

This works with ReadWriteOnce PVCs and the upgrade works also. Okay with a downtime, because it's only one controller.
