### ISSUE TITLE
Can't add annotations for controller.federation.mastersvc.type: LoadBalancer

### ISSUE THREAD

**Issue by 2stacks** [neuvector/neuvector-helm#121]
Unable to pass annotations in the helm chart to allow for internal loadbalancer.

```
annotations:
      # Classic ELB
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      # NLB
     service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
```
