### ISSUE TITLE
Document controller.configmap.data

### ISSUE THREAD

**Issue by gregsidelinger** [neuvector/neuvector-helm#160]
Document the settings that can go under each section of the configmap to help configure configure fresh installs.  Or at least link to another document.

```yaml
controller:
  configmap:
      data:
        # eulainitcfg.yaml: |
        #  ...
        # ldapinitcfg.yaml: |
        #  ...
        # oidcinitcfg.yaml: |
        # ...
        # samlinitcfg.yaml: |
        # ...
        # sysinitcfg.yaml: |
        # ...
        # userinitcfg.yaml: |
```
