### ISSUE TITLE
ServiceMonitor for neuvector/monitor chart

### ISSUE THREAD

**Issue by hairmare** [neuvector/neuvector-helm#164]
For users using a KubePrometheusStack (formerly known as prometheus-operator) style monitoring deployment, being able to deploy deploy a ServiceMonitor resource together with the exporter would be very handy.

In essence a ServiceMonitor is an alternative to scraping labeled exporters and it is supported by OpenShift as well as regular KuberPrometheusStack deployments.

Such a ServiceMonitor would look something like this:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nv-monitor
  labels:
    app: nv-monitor
spec:
  endpoints:
  - honorLabels: true
    interval: 60s
    # adapt to match the exporter
    path: /metrics
    scheme: http
    targetPort: 8080
  jobLabel: nv
  namespaceSelector:
    matchNames:
    - nv-namespace
  selector:
    matchLabels:
      app: nv-monitor
      release: nv-monitor
```

The ServiceMonitor would be an optional component that can be activated with something like `serviceMonitor.create`. For it to work a Service that point to the exporter would also be needed (and i'd consider that best-practice anyways).

Would you consider merging such a change? It's something I've seen a lot of charts offer and where available it's always highly appreciated by users.
