### ISSUE TITLE
how to get neuvector TargetGroup with port 443 instead of 30143

### ISSUE THREAD

**Issue by Srikanth1992** [neuvector/neuvector-helm#183]
Hi

I have installed neuvector using helm in eks cluster using the steps below:

- git clone https://github.com/neuvector/neuvector-helm
- created a new namespace
- helm install my-release --namespace neuvector ../../../neuvector-helm/charts/core/ -f values.yaml

Before installing made few changes to values.yaml under manager ingress section (https://github.com/neuvector/neuvector-helm/blob/master/charts/core/values.yaml#L262-L275)

Below are the changes: 
 ```
 ingress:
    enabled: true
    host:  pocnexuscontainer.XXXXXX.com # MUST be set, if ingress is enabled
    ingressClassName: "alb"
    path: "/"
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:AWSACCOUNTID:certificate/CertificateID
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    tls: true
    secretName: nexus-container-secret # my-tls-secret
```

When this was applied, helm was able to install all pods and create a loadbalancer in AWS, but when TargetGroup was created, it's created with port 30143 instead of 443.

I'd to know where to make changes in Values.yaml so that I can over-ride target group creation with 443 instead of 30143.

I had to manually created a TargetGroup with 443 & and register all the targets with port 30143 and updated the LoadBalancer listeners with the TargetGroup which was created manally which is when the DNS for neuvector is working for us. 

Let me know What changes I need to in values.yaml so that TargetGroup gets created with 443 and registeres all the targets with 30143 port

Thanks,
Srikanth
