### ISSUE TITLE
Add custom CA for Keycloak OIDC from Helm chart

### ISSUE THREAD

**Issue by nbisson** [neuvector/neuvector-helm#193]
Hi,

I deployed Neuvector by using neuvector-helm-chart and I would like to add the authentification by Keycloak (Open ID Connect).

My `values.yaml` configuration : 
``` yaml
controller:
  secret:
    enabled: true
    data:
      oidcinitcfg.yaml:
        Issuer: https://KEYCLOAK_URL/auth/realms/REALM
        Client_ID: neuvector
        Client_Secret: CLIENT_SECRET
        Scopes:
          - openid
          - profile
          - email
        Enable: true
        Default_Role: reader
```

However, I got the following error : 

```
2022-09-19T11:58:57.914|ERRO|CTL|rest.handlerAuthLoginServer: User login failed - error=Post "https://KEYCLOAK_URL/auth/realms/REALM/protocol/openid-connect/token": x509: certificate signed by unknown authority server=openId1 
```

The workaround would be to implement the ability to add your own CA from the chart. By adding the following content in the controller, the authentication works : 

```yaml
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-volume
          readOnly: true
#...
      volumes:
      - name: ca-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: custom-ca
```

What do you think about adding your own CA in the helm chart ?
