### ISSUE TITLE
Create servicemonitor for data exporter

### ISSUE THREAD

**Issue by rammanoj** [neuvector/neuvector-helm#293]
Create a servicemonitor to export the data from the service "neuvector-svc-prometheus-exporter" to Prometheus.

It's better to have a servicemonitor to automatically detect the neuvector exporter since kube-prometheus-stack has simplified the installation of Prometheus onto the cluster.

Happy to make a PR for it :-)

**Comment by 0Styless** [comment]
In my opinion, you can already do this with the monitor chart:

```yaml
exporter:
  enabled: true
  grafanaDashboard:
    enabled: true
  svc:
    enabled: true
    type: ClusterIP
  serviceMonitor:
    enabled: true
```
