### ISSUE TITLE
Neuvector SSO Failing in RKE2 Deployment 

### ISSUE THREAD

**Issue by Daemonslayer2048** [neuvector/neuvector-helm#356]
## Summary  
After installing Neuvector via the Rancher 2.8.0 UI I am unable to login to Neuvector via Rancher RBAC. I am simply met with an access denied after accepting the EULA, like below:  

![image](https://github.com/neuvector/neuvector-helm/assets/43078293/2593a41f-dc8e-4cb1-a3b0-aaaf0993d9cb)  

After reviewing the firefox console there is some interesting information
![image](https://github.com/neuvector/neuvector-helm/assets/43078293/569cac38-c2e8-4658-a11d-9c461169b342)  
The URL in question (https://rancher.k8s.lan/api/v1/namespaces/cattle-neuvector-system/services/https:neuvector-service-webui:8443/proxy/auth) when clicked returns: `Request is missing required HTTP header 'Token'` I am unsure if thats what you would expect necessarily. 

When I attempt to login I find the following related errors:  
```
ERRO|CTL|rest.sendRestReqInternal: Request failed - proxyOption=0 status=403 Forbidden timeout=10s url=https://rancher.k8s.lan/v3/users?me=true
ERRO|CTL|rest.checkRancherUserRole: - data=Forbidden err=403 Forbidden url=https://rancher.k8s.lan/v3/users?me=true
ERRO|CTL|rest.checkRancherUserRole: - proxyUsed=false statusCode=403 user=
```

I don't find any other relevant or useful errors that would explain in more detail what is going on. I have of course tried logging out and back in, different browsers, and incognito modes in case of a cached token. Are there relevant logs or locations I can check for debugging? 

## Software versions
Rancher: v2.8.0  
RKE2: v1.26.9+rke2r1 
Neuvector Helm: 103.0.0+up2.6.4  

__Note worthy setttings:__  
  - Cluster is running with Cilium CNI
  - SELinux: Enabled
  - CIS Profile: N/A

## Helm Values
```yaml
admissionwebhook:
  type: ClusterIP
autoGenerateCert: true
bottlerocket:
  enabled: false
  runtimePath: /run/dockershim.sock
containerd:
  enabled: false
  path: /var/run/containerd/containerd.sock
controller:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - neuvector-controller-pod
            topologyKey: kubernetes.io/hostname
          weight: 100
  annotations: {}
  apisvc:
    annotations: {}
    route:
      enabled: false
      host: null
      termination: passthrough
      tls: null
    type: null
  azureFileShare:
    enabled: false
    secretName: null
    shareName: null
  certificate:
    keyFile: tls.key
    pemFile: tls.pem
    secret: null
  configmap:
    data: null
    enabled: false
  disruptionbudget: 0
  enabled: true
  env: []
  federation:
    managedsvc:
      annotations: {}
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        enabled: false
        host: null
        ingressClassName: ''
        path: /
        secretName: null
        tls: false
      route:
        enabled: false
        host: null
        termination: passthrough
        tls: null
      type: null
    mastersvc:
      annotations: {}
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        enabled: false
        host: null
        ingressClassName: ''
        path: /
        secretName: null
        tls: false
      route:
        enabled: false
        host: null
        termination: passthrough
        tls: null
      type: null
  image:
    hash: null
    repository: rancher/mirrored-neuvector-controller
    tag: 5.2.2-s1
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: false
    host: null
    ingressClassName: ''
    path: /
    secretName: null
    tls: false
  internal:
    certificate:
      caFile: ca.crt
      keyFile: tls.key
      pemFile: tls.crt
      secret: neuvector-internal
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: null
  pvc:
    accessModes:
      - ReadWriteMany
    capacity: null
    enabled: true
    existingClaim: false
    storageClass: longhorn-slow
  ranchersso:
    enabled: true
  replicas: 3
  resources: {}
  schedulerName: null
  secret:
    data:
      userinitcfg.yaml:
        users:
          - Fullname: admin
            Password: null
            Role: admin
    enabled: false
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  tolerations: []
crdwebhook:
  enabled: true
  type: ClusterIP
crio:
  enabled: false
  path: /var/run/crio/crio.sock
cve:
  adapter:
    affinity: {}
    certificate:
      keyFile: tls.key
      pemFile: tls.pem
      secret: null
    enabled: false
    env: []
    harbor:
      protocol: https
      secretName: null
    image:
      hash: null
      repository: rancher/mirrored-neuvector-registry-adapter
      tag: 0.1.1-s1
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      enabled: false
      host: null
      ingressClassName: ''
      path: /
      secretName: null
      tls: false
    internal:
      certificate:
        caFile: ca.crt
        keyFile: tls.key
        pemFile: tls.crt
        secret: neuvector-internal
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    resources: {}
    route:
      enabled: true
      host: null
      termination: passthrough
      tls: null
    runAsUser: null
    svc:
      annotations: {}
      loadBalancerIP: null
      type: NodePort
    tolerations: []
  scanner:
    affinity: {}
    dockerPath: ''
    enabled: true
    env: []
    image:
      hash: null
      registry: ''
      repository: rancher/mirrored-neuvector-scanner
      tag: latest
    internal:
      certificate:
        caFile: ca.crt
        keyFile: tls.key
        pemFile: tls.crt
        secret: neuvector-internal
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    replicas: 3
    resources: {}
    runAsUser: 5400
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    tolerations: []
  updater:
    cacert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    enabled: true
    image:
      hash: null
      registry: ''
      repository: rancher/mirrored-neuvector-updater
      tag: latest
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    priorityClassName: null
    runAsUser: 5400
    schedule: 0 0 * * *
    secure: false
defaultValidityPeriod: 365
docker:
  path: /var/run/docker.sock
  enabled: false
enforcer:
  enabled: true
  env: []
  image:
    hash: null
    repository: rancher/mirrored-neuvector-enforcer
    tag: 5.2.2-s1
  internal:
    certificate:
      caFile: ca.crt
      keyFile: tls.key
      pemFile: tls.crt
      secret: neuvector-internal
  podAnnotations: {}
  podLabels: {}
  priorityClassName: null
  resources: {}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  updateStrategy:
    type: RollingUpdate
global:
  cattle:
    psp:
      enabled: false
    url: https://rancher.k8s.lan
internal:
  certmanager:
    enabled: false
    secretname: neuvector-internal
k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock
leastPrivilege: false
manager:
  affinity: {}
  certificate:
    keyFile: tls.key
    pemFile: tls.pem
    secret: null
  enabled: true
  env:
    envs: []
    ssl: true
  image:
    hash: null
    repository: rancher/mirrored-neuvector-manager
    tag: 5.2.2-s1
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: false
    host: null
    ingressClassName: ''
    path: /
    secretName: null
    tls: false
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: null
  resources: {}
  route:
    enabled: true
    host: null
    termination: passthrough
    tls: null
  runAsUser: 5400
  svc:
    annotations: {}
    loadBalancerIP: null
    type: NodePort
  tolerations: []
oem: null
openshift: false
rbac: true
registry: docker.io
resources: {}
serviceAccount: neuvector
```
