### ISSUE TITLE
Is there a way to disable normal login?

### ISSUE THREAD

**Issue by Pabloo-ss** [neuvector/neuvector-helm#435]
I have configured NV to use a SAML login and I would like to disable the normal login and just leave enable the SAML one. Is there any way to do this?
![image](https://github.com/user-attachments/assets/2a734bc6-2621-495d-8395-5bd87176dae2)

**Comment by mjnagel** [comment]
Also would love this feature for the future. We're using Istio and were able to block the path used by NeuVector for local auth with this AuthorizationPolicy, but the button does still show (just errors if you try and login that way):
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: neuvector-deny-local-login
  namespace: neuvector
spec:
  action: DENY
  selector:
    matchLabels:
      app: neuvector-manager-pod
  rules:
  - to:
    - operation:
        paths: ["/auth"]
        ports: ["8443"]
```
