### ISSUE TITLE
proxy configuration inside helm configuration?

### ISSUE THREAD

**Issue by nauni77** [neuvector/neuvector-helm#99]
Hello,

is it possible to define the "http" and "https" proxy inside helm configuration file? 

At the moment we need to configure this after installation at web frontend. It would be greate to configure the complete neuvector software at installation phase, without additional steps after installation.

TIA and best regards, Oli

**Comment by dgiebert** [comment]
I am having the same issue I assume, basically the backend is using HTTPS as the protocol on port 8443.

For an nginx ingress:
```yaml
manager:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
```

**Comment by nauni77** [comment]
This works for us ...

```
manager:
  env:
    ssl: false
  svc:
    type: ClusterIP
  ingress:
    host: neuvector-ciam-test.dev.noventigroup.com
    tls: true
    enabled: true
    path: "/"
    annotations:
      kubernetes.io/ingress.class: nginx
```

But it's not nice that this is not working OOTB - without setting env.ssl, ... .
